<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Advert;


/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCriteria($address, $type)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->andWhere('a.address = :address');
        $qb->setParameter('address', $address);

        $qb->join('a.type', 't');
        $qb->andWhere('t.gearType = :gearType');
        $qb->setParameter('gearType', $type);

        return $qb->getQuery()->getResult();
        //récupérer un tableau
    }
}
