<?php

namespace AppBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCritere($address, $type, $date)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.address')
            ->where('a.type', $type)
            ->andWhere('a.date', $date)
            ->addSelect('a.id')
            ->join('a.type', 't')
            ->addSelect('t.name');

        if ($type == null) {
            $qb->addSelect('a.date');
        } else {
            $qb->addSelect('a.title');
        }

        $qb->getQuery();
        return $qb->getResult();
        //récupérer un tableau
    }
}
