<?php

namespace AppBundle\Repository;

/**
 * CharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacteristicRepository extends \Doctrine\ORM\EntityRepository
{
}
